Add support for PyJwt_2_0_0
ahopkins/sanic-jwt pull request #206
Opened 2020-12-23 07:28 UTC by rahulraina7

## Goal
PyJWT just released v2.0.0 which breaks sanic-jwt due to https://github.com/jpadilla/pyjwt/issues/529

## Approach
Type checking before returning access token.

2020-12-25 10:28 UTC, ahopkins commented
Seems like a simple change. Would you be interested to pull together a PR?

2020-12-25 10:28 UTC, ahopkins approved these changes

2020-12-25 10:29 UTC, ahopkins commented
Looks like I need to fix the Travis builds. Will look into that next week and get this merged. Thanks for the PR

2020-12-25 10:30 UTC, ahopkins requested changes
Can you also update the requirements?

2020-12-28 03:29 UTC, rahulraina7 commented
> Can you also update the requirements?

Updated setup.py

2020-12-28 18:24 UTC, ahopkins approved these changes

2020-12-28 19:34 UTC, ahopkins commented
Can you take a look at the failing tests?

2020-12-29 09:49 UTC, rahulraina7 commented
Hi @ahopkins: I have fixed the tests. The suite is failing due to some issues with coverage, probably some configuration issues. I will try to have a look but if you know what this is about then that's better

2020-12-29 12:41 UTC, ahopkins commented
Awesome. I am not too worried about the codecov. Thanks for this  I will get the checks sorted out and merge.

2020-12-30 04:22 UTC, rahulraina7 commented
I have commented out the coverage combine command for now, since there aren't multiple coverage files to combine.

2021-01-05 00:54 UTC, stikks commented
Happy new year guys. Any idea when this PR might get merged into master and released.

2021-01-05 06:28 UTC, rahulraina7 commented
@ahopkins : I am freezing this project dependency on sanic - 20.9.1. Due to https://github.com/huge-success/sanic/issues/1989 for now. Either I can make those changes you suggested there or wait for sanic for the patch.

2021-01-05 06:47 UTC, ahopkins commented
I am pushing out a patch for that shortly.

2021-01-05 07:07 UTC, ahopkins commented
See #1993

2021-01-05 09:01 UTC, ahopkins requested changes
Small change to overcome the name registry and then ready to merge.

2021-01-05 09:01 UTC, ahopkins commented on tox.ini
> +    sanic==20.9.1
I am not going to merge this with a 20.9 dependency.

Just add this line to the top of `conftest.py` after the imports.

```python
Sanic.test_mode = True
```

2021-01-05 09:02 UTC, ahopkins commented on tox.ini
> +    sanic==20.9.1
In the coming weeks, we will release: https://github.com/sanic-org/sanic-test

It will automatically set that.

2021-01-05 09:52 UTC, ahopkins approved these changes

2021-01-05 09:53 UTC, merged

2021-01-05 10:05 UTC, ahopkins commented
Released. Thank you :clap: 

https://pypi.org/project/sanic-jwt/1.6.0/